<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\Admin\SensorController;
use App\Http\Controllers\Admin\AlertThresholdController;
use App\Http\Controllers\Admin\UserController;

// Public routes
Route::get('/', [PublicController::class, 'index'])->name('home');

// Auth routes (generated by Laravel UI)
Auth::routes();

// Admin routes
Route::prefix('admin')->middleware(['auth'])->name('admin.')->group(function () {
    // Dashboard
    Route::get('/', function () {
        return view('admin.dashboard');
    })->name('dashboard');
    
    // Sensors
    Route::resource('sensors', SensorController::class);
    Route::patch('/sensors/{sensor}/toggle', [SensorController::class, 'toggle'])->name('sensors.toggle');
    
    // Alert Thresholds
    Route::resource('thresholds', AlertThresholdController::class)->except(['destroy', 'create', 'store']);
    
    // Users (system admin only)
    Route::middleware(['role:admin'])->group(function () {
        Route::resource('users', UserController::class);
    });
    
    // Data Simulation Control
    Route::get('/simulation', function () {
        return view('admin.simulation');
    })->name('simulation');
    
    Route::post('/simulation/generate', function () {
        Artisan::call('aqi:generate');
        return back()->with('success', 'AQI data generated successfully');
    })->name('simulation.generate');
});